### ISSUE TITLE
UBI reforms that should be budget-neutral don't net out to neutral net household income

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-uk#126]
Sometimes reforms that take tax differences, divide by number of people, and assign UBIs, produce small changes to average net incomes; see https://github.com/UBICenter/personal-allowance/pull/1#issuecomment-844375067 for an example.

It'd be great to have a minimal working example of this. @inesfb @nikhilwoodruff

**Comment by nikhilwoodruff** [comment]
Yep, although to be clear this doesn't happen in the aggregate net_income, just household_net_income - the root cause being that household_net_income is clipped at zero, and therefore any income effects happening below zero aren't taken into account. I agree a MWE would be useful though
