### ISSUE TITLE
Marriage allowance

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-uk#149]
Marriage allowance is not modelled yet, but would be relatively simple to implement. It's a tax credit granting up to £250 to married couples or those in civil partnerships ([gov.uk source](https://www.gov.uk/marriage-allowance)). There is some element of choice here, so the implementation would have to likely select the optimal choice.

**Comment by nikhilwoodruff** [comment]
This is now [in the model](https://github.com/PolicyEngine/openfisca-uk/blob/fdc0f5f18c538a5e91fb4a55b56e31f6a8b03703/openfisca_uk/variables/finance/tax/income_tax/allowances.py#L48)), but we haven't yet got a unit test for it.

**Comment by MaxGhenis** [comment]
Added an issue for a unit test in https://github.com/PolicyEngine/openfisca-uk/issues/394
