### ISSUE TITLE
vary should return round numbers on the x axis

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-uk#160]
Net income and MTR charts show x values that are not round:
![Screenshot 2021-10-01 08 38 51](https://user-images.githubusercontent.com/6076111/135649502-5810f5e6-f368-4281-8e6b-e30f2338cca3.png)

It seems like it should be round, based on the `vary` code:

https://github.com/PolicyEngine/openfisca-uk/blob/65b2c87904e85d2469e1109ff8ba646904d752b3/openfisca_uk/tools/simulation.py#L204-L208

It would make PolicyEngine graphs easier to read if the x axis had round numbers.

**Comment by MaxGhenis** [comment]
@nikhilwoodruff today you mentioned that this could be due to an off-by-one error involving `linspace`, but searching the repo for `linspace` returns no results: https://github.com/PolicyEngine/openfisca-uk/search?q=linspace

**Comment by nikhilwoodruff** [comment]
@MaxGhenis the actual call to `np.linspace` occurs in `openfisca-core` ([here](https://github1s.com/openfisca/openfisca-core/blob/HEAD/openfisca_core/simulations/simulation_builder.py#L518-L522)). The solution was to add 1 to the number of steps in IndividualSim.
