### ISSUE TITLE
Update policy parameters for 2021

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-uk#171]
For example, OF sets Child Benefit at [21.05](https://github.com/PSLmodels/openfisca-uk/blob/master/openfisca_uk/parameters/benefit/child_benefit/amount/eldest.yaml) for eldest/only children, as of 2021-06-01, but it's currently [21.15](https://www.gov.uk/child-benefit/what-youll-get).

**Comment by nikhilwoodruff** [comment]
Think we can close this.
