### ISSUE TITLE
Cannot import use_current_parameters

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-uk#236]
This is causing issues for me locally running PolicyEngine:
```python
from openfisca_uk.reforms.presets.current_date import use_current_parameters
```
Works from within the openfisca-uk folder, but not outside it.

**Comment by nikhilwoodruff** [comment]
That is a bit strange - though the openfisca-uk folder was needed to circumvent disk writing restrictions on App Engine.
