### ISSUE TITLE
163% MTR for pension-age person with 0 income

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-uk#249]
Goes from 100% (correct due to pension credit) to 163% to 103%

![image](https://user-images.githubusercontent.com/6076111/135909542-d5f04f9b-2b05-4065-b83c-c876a8c25168.png)

**Comment by nikhilwoodruff** [comment]
This was an issue with pensioners also being assigned Universal Credit income (from the `claims_UC` switch overriding normal ineligibility). Fixed by #252

**Comment by MaxGhenis** [comment]
Verified: here's an 80-year-old with no income
![image](https://user-images.githubusercontent.com/6076111/136683319-e0c821b4-6891-493e-a684-8cccee6485e9.png)
