### ISSUE TITLE
Fix benefit receipt so taxes and benefits are properly comparable

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-uk#262]
There are still some factors causing misalignment in household comparisons between openfisca-uk and ukmod - child benefit receipt affects income tax, dividend taxation, and others.

**Comment by MaxGhenis** [comment]
Still relevant?

**Comment by nikhilwoodruff** [comment]
I think we can close this - there's not a clear line between handling claimed/not claimed elements of the tax-benefit system and different implementations: we should validate primarily against official statistics.
