### ISSUE TITLE
Add `Country` entity

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/openfisca-uk#400]
As we get around to adding logic for the Firm, we have a need for variables that are scalar values (e.g. business tax revenue change). To fix this, I propose to add a singular `Country` entity, in which every person is a member. Then, whenever we need a scalar variable, we can set it to be country-level.

**Comment by MaxGhenis** [comment]
Now `State` https://github.com/PolicyEngine/openfisca-uk/blob/master/openfisca_uk/entities.py
