### ISSUE TITLE
Check disability flags

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-uk#42]
e.g. ensure disability includes PIP, check how enhanced and severe align with @DeepakSingh98's [spreadsheet](https://docs.google.com/spreadsheets/d/1b4nsgjkunstQaYCH-_fzfJfAMFr3aNzfLqvVVbZUJoQ/edit?ts=5fb59120). Also compare to external published aggregates.

**Comment by nikhilwoodruff** [comment]
Both of these are now fulfilled, so closing.
