### ISSUE TITLE
Use legislative references for Working Tax Credit

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-uk#428]

**Comment by nikhilwoodruff** [comment]
Looked into this earlier: will add, but briefly: Tax Credits are legalised in the Tax Credits Act 2002, which defers all the details of their implementation to The Working Tax Credit (Entitlement and Maximum Rate) Regulations 2002, which is amended in future years. 

E.g. the disability conditions are actually here as well: https://www.legislation.gov.uk/uksi/2002/2005/schedule/1

**Comment by MaxGhenis** [comment]
I'm working on it in #426
