### ISSUE TITLE
Use microdf for poverty functions

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/openfisca-uk#81]
`microdf` added `poverty_rate`, `deep_poverty_rate`, `poverty_gap`, and `squared_poverty_gap` in https://github.com/PSLmodels/microdf/pull/160.

`openfisca-uk` could use this as well, though it'd likely be simpler once https://github.com/PSLmodels/microdf/issues/161 is addressed so the data doesn't have to be put into a DataFrame.

**Comment by nikhilwoodruff** [comment]
Is this still an aim? I'm still not sure where exactly to handle these headline figure calculations.

**Comment by nikhilwoodruff** [comment]
I think we can close this - poverty calculations use microdf and I think keeping the country-specific code away from microdf is more suitable.
